blank_issues_enabled: true
contact_links:
  - name: ğŸ“‚ undiscovered Repositories
    url: https://github.com/debrajhyper?tab=repositories
    about: View the repositories you probably missed.
  - name: ğŸ‘©â€ğŸ’» World of Zero @Port
    url: https://kiwismedia.com/@debraj
    about: join the world of creators, makers, builders, designers, educators, content writers & developers.